### PR TITLE
Fix deadlock problem in node_processor close

### LINKED ISSUE #42: The NodeProcessor.Close method dead-lock problem.
InfluxDB cluster: v1.8.10-c1.1.2
OS: CentOS 7.9
Hardware: 64C128G

1. Make the condition that hh.service.purgeInactiveProcessors() call p.Close()  ---- services/hh/service.go : 374
2. If the node-processor is in run(), it will blocked. ---- services/hh/node_processor.go : 254
3. hh.service.WriteShard() goroutine all blocked ----  services/hh/service.go : 262

Expected behavior:
The NodeProcessor will be closed normally.

Actual behavior:
The goroutine call NodeProcessor::Close() will be blocked by the wg.
And the NodeProcessor::run if calling SendWrite() will be blocked by mu.
DEAD-LOCK!

The NodeProcessor::Close()  is called by the hh.service.purgeInactiveProcessors(), which hold the s.mu,
So ALL the hh.service.WriteShard will be blocked by s.mu. 

Sorry the pprof file is in the internal server of the company.

### PR DESCRIPTION
**Pull request by defttycom**
**Which Issue(s) This PR Fixes**
Fixes https://github.com/chengshiwen/influxdb-cluster/issues/42

**Brief Description**
Resolve the dead lock in NodeProcess.Close() method.

### CODE REVIEW

File: services/hh/node_processor.go [hunk 1]
```diff
@@ -107,16 +107,18 @@ func (n *NodeProcessor) Open() error {
...
 		// Already closed.
+		n.mu.Unlock()
 		return nil
 	}
 
 	close(n.done)
-	n.wg.Wait()
 	n.done = nil
+	n.mu.Unlock()
+
```
Comment (chengshiwen) [inline services/hh/node_processor.go:120]: Pls remove this empty line 120

Comment (defttycom) [reply services/hh/node_processor.go]: Done.
